name: Python application

on:
  schedule:
    - cron: '0 11 * * *'  # Executa às 8h00 BRT (11h00 UTC)
    - cron: '0 20 * * *'  # Executa às 17h00 BRT (20h00 UTC)
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run webscrapper script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Token do Telegram
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}  # IDs de chat (separados por vírgula)
        run: python webscrapper.py

      - name: Upload SQLite database
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-database  # Nome do artefato no GitHub Actions
          path: scrapper.db      # Caminho para o banco gerado na raiz do projeto
